# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Moises Echeverria Ortiz
title: Estudiante de ingeniería en computación
email: moises.echeverria5780@alummos.udg.mx
# email_title: Email (Email title override)
phone: 3321999698
# phone_title: Phone (Phone title override)
website: https://moiseseo.github.io/
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: jekyllrb
github_username: MoisesEO
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
instagram_username: moysesotz55
linkedin_username: moises-echeverria-ortiz-8117a5324
pinterest_username: moysesortiz55
youtube_username: MoisesEOrtiz
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
#additional_links:
############## AQUI EMPIEZA ##############
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

############## TERMINA AQUI ##############

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/zorro_perfil.jpg
about_content: | # this will include new lines to allow paragraphs
  Soy una persona bastante seria, responsable y que le encanta aprender de sus errores mientras se divierte y mejora, se trabajar en equipo, no tengo grandes rasgos de lider, pero puedo cumplir con los objetivos que se establezcan y se escuchar y aprender de las ideas de los demas para mejorar mi punto de vista.
  

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Proyecto Universitario sobre el aprovechamiento de residuos de café.

        ########### Inicio comentarios ###########
        #link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #link_text: Link Text
        #additional_links:
        #  - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #    icon: fab fa-github
        #    url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #  - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #    icon: fab fa-github
        #    url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)

        ########### Final del comentario ###########
        quote: >
          Proyecto realizado para una materia de la universidad (Seminario de solución de problemas de métodos matemáticos III)
        description: | # this will include new lines to allow paragraphs
          En ese proyecto participe en el apartado de programación dado a que participamos alrededor de 40 personas las cuales estaban dedicadas a distintas áreas, participe en la programación y creación de la interfaz grafica y manejo de base de datos, así como su conexión entre ellas haciendo 5 JFrames para la aplicación final.
  
  - title: Experience
    layout: list
    content:
      - layout: top
        title: Prepa 19
        sub_title: Diseño de un videojuego educativo en realidad virtual
        caption: Septiembre 2024 - presente)
        #link: Link to company (optional)
        quote: >
          Preparatoria No. 19 de UdeG.
        description: | # this will include new lines to allow paragraphs
          Tal cual no es un trabajo formal, pero es mi servicio socia donde deberé junto a otros compañeros, desarrollar un videojuego en realidad virtual usando Unity. El objetivo de este videojuego es incentivar a que los estudiantes universitarios a desarrollar sus conocimientos interactuando con los distintos objetos que serán representados en el juego.
  - title: Education
    layout: list
    content:
      - layout: top
        title: Universidad De Guadalajara
        sub_title: Licenciatura en ingeniería en Computación 
        caption: (2021 - 2024)
        quote: >
          Cursada en el Centro Universitario de Ciencias Exactas e Ingenierías (CUCEI) 
        description: | # this will include new lines to allow paragraphs
          Durante mi estancia en la universidad (espero terminar todas mis materias este semestre, del titulo hablaremos luego) he aprendido diversas habilidades para poder trabajar en equipo, lenguajes de programación y ampliar mi campo de visión, pero esto no termina aquí, planeo seguir capacitándome con cursos para no parar de aprender ya que este tipo de carreras siempre se puede aprender uno nuevo dado a que nunca terminan de avanzar.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Me gustan mucho los videojuegos, escuchar música y los deportes, siempre intento hacer algo nuevo aun que a veces mi estado de animo no me lo permite, siempre pueden contar con un buen amigo, que los escuche e intente ayudar a pesar de que no siempre tengo las respuestas para todo.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
